---
AWSTemplateFormatVersion: "2010-09-09"
Description: "JAMstack Application - S3, CloudFront, API Gateway, Lambda,
  DynamoDB"

Parameters:
  BudgetNotificationEmail:
    Type: String
    Description: Email address for AWS budget notifications
    AllowedPattern: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    ConstraintDescription: Must be a valid email address
  LogRetentionDays:
    Type: Number
    Description: Number of days to retain logs
    Default: 90
    MinValue: 1
    MaxValue: 3653
# This is here as a placeholder for future domain name integration
# Deactivated for now to silence warnings
#   DomainName:
#     Type: String
#     Description: Domain name for the application
#     Default: example.com

Resources:
  # S3 Bucket for logs
  LogsBucket:
    Type: AWS::S3::Bucket
    Metadata:
      guard:
        SupressedRules:
          - S3_BUCKET_LOGGING_ENABLED
          - S3_BUCKET_VERSIONING_ENABLED
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub "${AWS::StackName}-logs"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldLogs
            Status: Enabled
            ExpirationInDays: !Ref LogRetentionDays
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

  AccessLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogsBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: S3ServerAccessLogsPolicy
            Effect: Allow
            Principal:
              Service: logging.s3.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${LogsBucket.Arn}/static-content-logs/*"
            Condition:
              StringEquals:
                "aws:SourceAccount": !Ref AWS::AccountId
          - Sid: CloudFrontAccessLogsPolicy
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:PutObject
            Resource: !Sub "${LogsBucket.Arn}/cloudfront-logs/*"
            Condition:
              StringEquals:
                "aws:SourceAccount": !Ref AWS::AccountId

  # S3 Bucket for static content
  StaticContentBucket:
    Type: AWS::S3::Bucket
    Metadata:
      guard:
        SupressedRules:
          - S3_BUCKET_VERSIONING_ENABLED
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      BucketName: !Sub "${AWS::StackName}-static-content"
      LoggingConfiguration:
        DestinationBucketName: !Ref LogsBucket
        LogFilePrefix: static-content-logs/
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # S3 Bucket Policy for CloudFront access
  StaticContentBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticContentBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource:
              - !GetAtt StaticContentBucket.Arn
              - !Sub "${StaticContentBucket.Arn}/*"
            Condition:
              StringEquals:
                "aws:SourceArn": !Sub "arn:${AWS::Partition}:cloudfront::\
                  ${AWS::AccountId}:distribution/${CloudFrontDistribution}"
          - Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !GetAtt StaticContentBucket.Arn
              - !Sub "${StaticContentBucket.Arn}/*"
            Condition:
              Bool:
                "aws:SecureTransport": false

  # CloudFront Origin Access Control
  OriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub "${AWS::StackName}-oac"
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # Custom Origin Request Policy for API Gateway
  ApiOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub "${AWS::StackName}-api-origin-policy"
        QueryStringsConfig:
          QueryStringBehavior: all
        HeadersConfig:
          HeaderBehavior: none
        CookiesConfig:
          CookieBehavior: none

  # DynamoDB Table
  DataTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub "${AWS::StackName}-data"
      SSESpecification:
        SSEEnabled: true
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: event_date
          AttributeType: S
        - AttributeName: event_datetime
          AttributeType: S
      KeySchema:
        - AttributeName: event_date
          KeyType: HASH
        - AttributeName: event_datetime
          KeyType: RANGE

  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role\
          /AWSLambdaBasicExecutionRole"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AWSXRayDaemonWriteAccess"
        - !Ref DynamoDBAccessPolicy

  # DynamoDB Access Policy
  DynamoDBAccessPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
              - dynamodb:Query
            Resource: !GetAtt DataTable.Arn

  # CloudWatch Log Group for SubmitNumberFunction
  SubmitNumberLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AWS::StackName}-submit-number"
      RetentionInDays: !Ref LogRetentionDays

  # Lambda Function (Submit number)
  SubmitNumberFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-submit-number"
      # TODO: set VPC configuration if needed
      Runtime: python3.14
      Handler: submit_number.handler
      Architectures:
        - arm64
      Role: !GetAtt LambdaExecutionRole.Arn
      TracingConfig:
        Mode: Active
      Environment:
        Variables:
          TABLE_NAME: !Ref DataTable
      Code:
        ZipFile: |
          # Lambda code will be deployed separately
          # See ../backend/submit_number.py for the actual implementation
          import json
          def handler(event, context):
            return {
              'statusCode': 200,
              'body': json.dumps({'message': 'Deploy backend code separately'})
            }

  # API Gateway
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${AWS::StackName}-api"
      EndpointConfiguration:
        Types:
          - REGIONAL

  # IAM Role for API Gateway CloudWatch Logging
  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role\
          /AmazonAPIGatewayPushToCloudWatchLogs"

  # API Gateway Account Settings
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn

  # CloudWatch Log Group for API Gateway
  ApiGatewayLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/apigateway/${AWS::StackName}"
      RetentionInDays: !Ref LogRetentionDays

  # API Gateway Resources (api/data)
  ApiRoot:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: api

  # Request Validator
  ApiRequestValidator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      RestApiId: !Ref ApiGateway
      Name: !Sub "${AWS::StackName}-validator"
      ValidateRequestBody: true
      ValidateRequestParameters: true

  # Request Model for SubmitNumber
  SubmitNumberModel:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !Ref ApiGateway
      ContentType: application/json
      Name: SubmitNumberModel
      Schema:
        $schema: "http://json-schema.org/draft-04/schema#"
        type: object
        required:
          - number
          - timestamp
        properties:
          number:
            type: integer
            minimum: 1
            maximum: 10
          timestamp:
            type: string
          location:
            type:
              - object
              - "null"
            required:
              - latitude
              - longitude
            properties:
              latitude:
                type: number
                minimum: -90
                maximum: 90
              longitude:
                type: number
                minimum: -180
                maximum: 180

  SubmitNumberResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref ApiRoot
      PathPart: submit-number

  # API Gateway Method
  SubmitNumberMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref SubmitNumberResource
      HttpMethod: POST
      AuthorizationType: NONE
      RequestValidatorId: !Ref ApiRequestValidator
      RequestModels:
        application/json: !Ref SubmitNumberModel
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub "arn:${AWS::Partition}:apigateway:${AWS::Region}\
          :lambda:path/2015-03-31/functions/${SubmitNumberFunction.Arn}/invocations"

  # SubmitNumberFunction Permission for API Gateway
  SubmitNumberFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref SubmitNumberFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:\
        ${AWS::AccountId}:${ApiGateway}/*/POST/api/submit-number"

  # CloudWatch Log Group for StatsFunction
  StatsLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AWS::StackName}-stats"
      RetentionInDays: !Ref LogRetentionDays

  # Lambda Function (Stats)
  StatsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-stats"
      Runtime: python3.14
      Handler: stats.handler
      Architectures:
        - arm64
      Role: !GetAtt LambdaExecutionRole.Arn
      TracingConfig:
        Mode: Active
      Environment:
        Variables:
          TABLE_NAME: !Ref DataTable
      Code:
        ZipFile: |
          # Lambda code will be deployed separately
          # See ../backend/stats.py for the actual implementation
          import json
          def handler(event, context):
            return {
              'statusCode': 200,
              'body': json.dumps({'message': 'Deploy backend code separately'})
            }

  # API Gateway Resource for stats
  StatsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !Ref ApiRoot
      PathPart: stats

  # API Gateway Method for stats (GET)
  StatsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref StatsResource
      HttpMethod: GET
      AuthorizationType: NONE
      RequestValidatorId: !Ref ApiRequestValidator
      RequestParameters:
        method.request.querystring.to: true
        method.request.querystring.from: true
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        RequestParameters:
          integration.request.querystring.to: "method.request.querystring.to"
          integration.request.querystring.from: "method.request.querystring.\
            from"
        Uri: !Sub "arn:${AWS::Partition}:apigateway:${AWS::Region}\
          :lambda:path/2015-03-31/functions/${StatsFunction.Arn}/invocations"

  # StatsFunction Permission for API Gateway
  StatsFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StatsFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:${AWS::Partition}:execute-api:${AWS::Region}:\
        ${AWS::AccountId}:${ApiGateway}/*/GET/api/stats"

  # API Gateway Deployment
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - SubmitNumberMethod
      - StatsMethod
    Properties:
      RestApiId: !Ref ApiGateway
      Description: !Sub "Deployment for ${AWS::StackName} with\
        submit-number and stats endpoints"

  # API Gateway Stage with logging
  ApiGatewayStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      RestApiId: !Ref ApiGateway
      DeploymentId: !Ref ApiDeployment
      StageName: prod
      TracingEnabled: true
      AccessLogSetting:
        DestinationArn: !GetAtt ApiGatewayLogGroup.Arn
        Format: "$context.requestId $context.identity.sourceIp \
          $context.requestTime $context.httpMethod $context.resourcePath \
          $context.status $context.protocol"
      MethodSettings:
        - ResourcePath: "/*"
          LoggingLevel: INFO
          HttpMethod: "*"
          ThrottlingBurstLimit: 100
          ThrottlingRateLimit: 50

  # API Gateway Usage Plan
  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: !Sub "${AWS::StackName}-usage-plan"
      Throttle:
        BurstLimit: 100
        RateLimit: 50
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: !Ref ApiGatewayStage

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Logging:
          Bucket: !GetAtt LogsBucket.DomainName
          Prefix: cloudfront-logs/
          IncludeCookies: false
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt StaticContentBucket.RegionalDomainName
            S3OriginConfig: {}
            OriginAccessControlId: !Ref OriginAccessControl
          - Id: ApiOrigin
            DomainName: !Sub "${ApiGateway}.execute-api.${AWS::Region}\
              .amazonaws.com"
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
            OriginPath: /prod
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          ResponseHeadersPolicyId: !Ref SecurityHeadersPolicy
          Compress: true
        CacheBehaviors:
          - PathPattern: /api/*
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            OriginRequestPolicyId: !Ref ApiOriginRequestPolicy
        DefaultRootObject: index.html
        Enabled: true
        IPV6Enabled: true
        PriceClass: PriceClass_100

  # CloudFront Response Headers Policy for Security
  SecurityHeadersPolicy:
    Type: AWS::CloudFront::ResponseHeadersPolicy
    Properties:
      ResponseHeadersPolicyConfig:
        Name: !Sub "${AWS::StackName}-security-headers"
        SecurityHeadersConfig:
          StrictTransportSecurity:
            AccessControlMaxAgeSec: 63072000
            IncludeSubdomains: true
            Override: true
          ContentTypeOptions:
            Override: true
          FrameOptions:
            FrameOption: DENY
            Override: true
          XSSProtection:
            ModeBlock: true
            Protection: true
            Override: true
          ReferrerPolicy:
            ReferrerPolicy: strict-origin-when-cross-origin
            Override: true

  # AWS Budget for cost monitoring
  ApplicationBudget:
    Type: AWS::Budgets::Budget
    Properties:
      Budget:
        BudgetName: !Sub "${AWS::StackName}-monthly-budget"
        BudgetLimit:
          Amount: "100"
          Unit: USD
        TimeUnit: MONTHLY
        BudgetType: COST
      NotificationsWithSubscribers:
        - Notification:
            NotificationType: FORECASTED
            ComparisonOperator: GREATER_THAN
            Threshold: 80
            ThresholdType: PERCENTAGE
          Subscribers:
            - SubscriptionType: EMAIL
              Address: !Ref BudgetNotificationEmail

Outputs:
  CloudFrontURL:
    Description: CloudFront Distribution URL
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"

  S3BucketName:
    Description: S3 Bucket for static content
    Value: !Ref StaticContentBucket

  SubmitNumberFunctionName:
    Description: Lambda function name for submit-number function
    Value: !Ref SubmitNumberFunction

  StatsFunctionName:
    Description: Lambda function name for stats function
    Value: !Ref StatsFunction
